# Generated by Django 5.1.4 on 2026-09-09 19:49

import django.db.models.deletion
import services.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_rls'),
        ('tenants', '0003_alter_tenant_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('khatmah', 'ختمة'), ('pages', 'صفحات يوميًا')], default='khatmah', max_length=12)),
                ('pages_per_day', models.PositiveSmallIntegerField(default=2)),
                ('current_page', models.PositiveSmallIntegerField(default=1)),
                ('start_page', models.PositiveSmallIntegerField(default=1)),
                ('riwayah', models.CharField(default='hafs_asim', max_length=32)),
                ('status', models.CharField(choices=[('active', 'نشطة'), ('paused', 'متوقفة'), ('completed', 'مكتملة')], default='active', max_length=12)),
                ('started_on', models.DateField()),
                ('target_date', models.DateField(blank=True, null=True)),
                ('khatmat', models.PositiveSmallIntegerField(default=0)),
                ('reminder_time', models.CharField(blank=True, max_length=5)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_plans', to='people.person')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'reading_plan',
            },
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_date', models.DateField()),
                ('from_page', models.PositiveSmallIntegerField()),
                ('to_page', models.PositiveSmallIntegerField()),
                ('minutes', models.PositiveSmallIntegerField(default=0)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='reading.readingplan')),
            ],
            options={
                'db_table': 'reading_log',
            },
        ),
        migrations.AddIndex(
            model_name='readingplan',
            index=models.Index(fields=['tenant', 'person', 'status'], name='reading_pla_tenant__23bec6_idx'),
        ),
        migrations.AddIndex(
            model_name='readinglog',
            index=models.Index(fields=['tenant', 'plan', 'on_date'], name='reading_log_tenant__d4b575_idx'),
        ),
    ]
