# Generated by Django 5.1.4 on 2026-09-08 14:29

import django.db.models.deletion
import services.common.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consent',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_type', models.CharField(max_length=24)),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=8)),
                ('evidence_ref', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'people_consent',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='active', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'people_enrollment',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('communication_preferences', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'people_guardian',
            },
        ),
        migrations.CreateModel(
            name='GuardianLink',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(default='parent', max_length=20)),
                ('primary', models.BooleanField(default=True)),
                ('finance_visibility', models.BooleanField(default=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'people_guardian_link',
            },
        ),
        migrations.CreateModel(
            name='Halaqah',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('in_person', 'حضوري'), ('online', 'عن بُعد'), ('hybrid', 'مدمج')], default='in_person', max_length=12)),
                ('gender_policy', models.CharField(default='mixed', max_length=8)),
                ('capacity', models.PositiveSmallIntegerField(default=15)),
                ('riwayah', models.CharField(default='hafs_asim', max_length=32)),
                ('mushaf_type', models.CharField(default='madani_15_line', max_length=32)),
                ('policy_key', models.CharField(default='sabaq_sabqi_manzil', max_length=40)),
                ('schedule_summary', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='active', max_length=12)),
            ],
            options={
                'db_table': 'people_halaqah',
            },
        ),
        migrations.CreateModel(
            name='HalaqahStaff',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(default='teacher', max_length=12)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'people_halaqah_staff',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('display_name_ar', models.CharField(max_length=200)),
                ('display_name_en', models.CharField(blank=True, max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=8)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('photo_key', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(default='active', max_length=16)),
            ],
            options={
                'db_table': 'people_person',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('staff_type', models.CharField(choices=[('teacher', 'معلم'), ('assistant', 'معلم مساعد'), ('supervisor', 'مشرف'), ('admin', 'إداري'), ('finance', 'مالية'), ('hr', 'موارد بشرية'), ('instructor', 'مدرب'), ('support', 'دعم')], default='teacher', max_length=12)),
                ('qualifications', models.JSONField(default=list)),
                ('riwayat', models.JSONField(default=list)),
                ('max_load', models.PositiveSmallIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'people_staff',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student_code', models.CharField(blank=True, max_length=32)),
                ('level', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('applicant', 'متقدم'), ('active', 'نشط'), ('paused', 'متوقف'), ('left', 'منسحب'), ('alumni', 'خريج')], default='active', max_length=12)),
                ('is_minor', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'people_student',
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('on_date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('excused', 'بعذر'), ('left_early', 'انصرف مبكرًا')], default='present', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'people_attendance',
            },
        ),
    ]
