# Generated by Django 5.1.4 on 2026-09-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuranRelease',
            fields=[
                ('version', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('riwayah', models.CharField(max_length=32)),
                ('text_root_sha256', models.CharField(max_length=64)),
                ('manifest', models.JSONField()),
                ('loaded_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'quran_release',
            },
        ),
        migrations.CreateModel(
            name='Ayah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riwayah', models.CharField(max_length=32)),
                ('ayah_index', models.PositiveIntegerField()),
                ('surah', models.PositiveSmallIntegerField()),
                ('ayah', models.PositiveSmallIntegerField()),
                ('key', models.CharField(max_length=8)),
                ('text_uthmani', models.TextField()),
                ('word_count', models.PositiveSmallIntegerField()),
                ('page', models.PositiveSmallIntegerField()),
                ('juz', models.PositiveSmallIntegerField()),
                ('hizb', models.PositiveSmallIntegerField()),
                ('rub', models.PositiveSmallIntegerField()),
                ('sha256', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'quran_ayah',
                'indexes': [models.Index(fields=['riwayah', 'surah', 'ayah'], name='quran_ayah_riwayah_fe8ed8_idx'), models.Index(fields=['riwayah', 'page'], name='quran_ayah_riwayah_87c90b_idx')],
                'unique_together': {('riwayah', 'ayah_index')},
            },
        ),
        migrations.CreateModel(
            name='Surah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riwayah', models.CharField(max_length=32)),
                ('number', models.PositiveSmallIntegerField()),
                ('ayah_count', models.PositiveSmallIntegerField()),
                ('start_index', models.PositiveIntegerField()),
                ('name_ar', models.CharField(max_length=64)),
                ('name_tr', models.CharField(max_length=64)),
                ('name_en', models.CharField(max_length=64)),
                ('revelation', models.CharField(max_length=10)),
                ('revelation_order', models.PositiveSmallIntegerField()),
                ('rukus', models.PositiveSmallIntegerField()),
            ],
            options={
                'db_table': 'quran_surah',
                'unique_together': {('riwayah', 'number')},
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('riwayah', models.CharField(max_length=32)),
                ('unit_type', models.CharField(max_length=8)),
                ('number', models.PositiveSmallIntegerField()),
                ('first_ayah_index', models.PositiveIntegerField()),
                ('last_ayah_index', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'quran_unit',
                'unique_together': {('riwayah', 'unit_type', 'number')},
            },
        ),
    ]
