# Generated by Django 5.1.4 on 2026-09-08 18:39

import django.core.validators
import django.db.models.deletion
import services.common.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0003_rls'),
        ('tenants', '0002_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeePlan',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('cadence', models.CharField(choices=[('monthly', 'شهري'), ('term', 'فصلي'), ('annual', 'سنوي'), ('one_time', 'مرة واحدة')], default='monthly', max_length=10)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('currency', models.CharField(default='JOD', max_length=3)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sibling_discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_plans', to='tenants.branch')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'finance_fee_plan',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20)),
                ('payer_name', models.CharField(blank=True, max_length=200)),
                ('issued_on', models.DateField()),
                ('due_on', models.DateField()),
                ('currency', models.CharField(default='JOD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('discount_total', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('paid_total', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('issued', 'صادرة'), ('partially_paid', 'مدفوعة جزئيًا'), ('paid', 'مدفوعة'), ('overdue', 'متأخرة'), ('void', 'ملغاة')], db_index=True, default='issued', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('period_label', models.CharField(blank=True, db_index=True, max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='people.student')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'finance_invoice',
                'ordering': ['-issued_on', '-number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=8)),
                ('unit_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('kind', models.CharField(choices=[('fee', 'رسوم'), ('discount', 'خصم'), ('scholarship', 'منحة'), ('adjustment', 'تسوية')], default='fee', max_length=12)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.invoice')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'finance_invoice_line',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentFeePlan',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('discount_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('scholarship_pct', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('scholarship_note', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'نشط'), ('ended', 'منتهٍ')], default='active', max_length=8)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='finance.feeplan')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_plans', to='people.student')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'finance_student_fee_plan',
                'ordering': ['-start_date'],
                'unique_together': {('student', 'plan', 'start_date')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='source_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.studentfeeplan'),
        ),
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=32)),
                ('next_value', models.PositiveIntegerField(default=1)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'finance_number_sequence',
                'unique_together': {('tenant', 'key')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('currency', models.CharField(default='JOD', max_length=3)),
                ('method', models.CharField(choices=[('cash', 'نقدًا'), ('bank_transfer', 'تحويل بنكي'), ('card_manual', 'بطاقة (يدوي)'), ('other', 'أخرى')], default='cash', max_length=16)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('received_on', models.DateField()),
                ('note', models.CharField(blank=True, max_length=300)),
                ('receipt_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('posted', 'مسجلة'), ('refunded', 'مستردة')], db_index=True, default='posted', max_length=10)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('refund_reason', models.CharField(blank=True, max_length=300)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.invoice')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'finance_payment',
                'ordering': ['-received_on', '-created_at'],
                'unique_together': {('tenant', 'receipt_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('tenant', 'number')},
        ),
    ]
