# Generated by Django 5.1.4 on 2026-09-08 14:29

import services.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AyahStateEvent',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ayah_index', models.PositiveIntegerField()),
                ('prev_state', models.CharField(max_length=16)),
                ('new_state', models.CharField(max_length=16)),
                ('prev_score', models.FloatField()),
                ('new_score', models.FloatField()),
                ('cause', models.CharField(max_length=16)),
                ('cause_ref', models.UUIDField(blank=True, null=True)),
                ('engine_version', models.CharField(max_length=20)),
                ('occurred_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hifz_ayah_state_event',
            },
        ),
        migrations.CreateModel(
            name='DailyPlan',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan_date', models.DateField()),
                ('status', models.CharField(choices=[('proposed', 'مقترحة'), ('approved', 'معتمدة'), ('edited', 'معدّلة'), ('overridden', 'مستبدلة'), ('done', 'منجزة'), ('carried', 'مرحّلة')], default='proposed', max_length=12)),
                ('rationale', models.JSONField(default=list)),
                ('paused_new', models.BooleanField(default=False)),
                ('planner_version', models.CharField(default='planner/v1', max_length=20)),
            ],
            options={
                'db_table': 'hifz_daily_plan',
            },
        ),
        migrations.CreateModel(
            name='JourneyEvent',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('occurred_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'hifz_journey_event',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='MistakeEvent',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ayah_index', models.PositiveIntegerField()),
                ('word_position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('mistake_type', models.CharField(max_length=40)),
                ('severity', models.CharField(default='major', max_length=8)),
                ('confused_with_ayah_index', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'hifz_mistake_event',
            },
        ),
        migrations.CreateModel(
            name='MistakeType',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=40)),
                ('name_ar', models.CharField(max_length=80)),
                ('name_en', models.CharField(blank=True, max_length=80)),
                ('default_weight', models.FloatField(default=0.5)),
                ('default_severity', models.CharField(default='minor', max_length=8)),
            ],
            options={
                'db_table': 'hifz_mistake_type',
            },
        ),
        migrations.CreateModel(
            name='PlanAction',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=16)),
                ('before', models.JSONField(blank=True, null=True)),
                ('after', models.JSONField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'hifz_plan_action',
            },
        ),
        migrations.CreateModel(
            name='PlanSegment',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(max_length=16)),
                ('from_ayah_index', models.PositiveIntegerField()),
                ('to_ayah_index', models.PositiveIntegerField()),
                ('pages', models.JSONField(default=list)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('repetitions_required', models.PositiveSmallIntegerField(default=1)),
                ('completion', models.CharField(default='pending', max_length=16)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'hifz_plan_segment',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='QuranJourney',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('riwayah', models.CharField(default='hafs_asim', max_length=32)),
                ('mushaf_type', models.CharField(default='madani_15_line', max_length=32)),
                ('policy_key', models.CharField(default='sabaq_sabqi_manzil', max_length=40)),
                ('policy_overrides', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('memorizing', 'في الحفظ'), ('retaining', 'في المراجعة الطويلة'), ('paused', 'متوقف'), ('completed_with_retention', 'أتمّ الختم'), ('ijazah_track', 'مسار الإجازة')], default='memorizing', max_length=32)),
                ('started_at', models.DateField()),
                ('direction', models.CharField(default='backward', max_length=12)),
                ('current_ayah_index', models.PositiveIntegerField(blank=True, null=True)),
                ('level', models.CharField(blank=True, max_length=40)),
                ('quran_core_version', models.CharField(default='0.1.0', max_length=20)),
                ('memorized_ayat', models.PositiveIntegerField(default=0)),
                ('strong_ayat', models.PositiveIntegerField(default=0)),
                ('needs_revision_ayat', models.PositiveIntegerField(default=0)),
                ('weak_ayat', models.PositiveIntegerField(default=0)),
                ('critical_ayat', models.PositiveIntegerField(default=0)),
                ('mastered_ayat', models.PositiveIntegerField(default=0)),
                ('avg_retention', models.FloatField(default=0.0)),
                ('memorized_pages_order', models.JSONField(default=list)),
            ],
            options={
                'db_table': 'hifz_journey',
            },
        ),
        migrations.CreateModel(
            name='RecitationSession',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(default='near', max_length=16)),
                ('from_ayah_index', models.PositiveIntegerField()),
                ('to_ayah_index', models.PositiveIntegerField()),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('outcome', models.CharField(choices=[('pass', 'اجتاز'), ('repeat', 'يعيد'), ('partial', 'جزئي')], default='pass', max_length=8)),
                ('grade', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('note_visibility', models.CharField(default='parent', max_length=12)),
                ('source', models.CharField(default='in_person', max_length=16)),
                ('idempotency_key', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'db_table': 'hifz_recitation_session',
            },
        ),
        migrations.CreateModel(
            name='StudentAyahState',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ayah_index', models.PositiveIntegerField()),
                ('state', models.CharField(default='not_memorized', max_length=16)),
                ('retention_score', models.FloatField(default=0.0)),
                ('stability_days', models.FloatField(default=0.0)),
                ('memorized_at', models.DateTimeField(blank=True, null=True)),
                ('last_recited_at', models.DateTimeField(blank=True, null=True)),
                ('last_passed_at', models.DateTimeField(blank=True, null=True)),
                ('last_fail_at', models.DateTimeField(blank=True, null=True)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('fail_count', models.PositiveIntegerField(default=0)),
                ('consecutive_successes', models.PositiveIntegerField(default=0)),
                ('next_due_at', models.DateTimeField(blank=True, null=True)),
                ('student_factor', models.FloatField(default=1.0)),
                ('override_state', models.CharField(blank=True, max_length=16, null=True)),
                ('engine_version', models.CharField(default='retention/v1', max_length=20)),
            ],
            options={
                'db_table': 'hifz_ayah_state',
            },
        ),
    ]
