# Generated by Django 5.1.4 on 2026-09-08 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hifz', '0001_initial'),
        ('people', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ayahstateevent',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='journeyevent',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journeyevent',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mistakeevent',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mistaketype',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='planaction',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='planaction',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='hifz.dailyplan'),
        ),
        migrations.AddField(
            model_name='planaction',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='plansegment',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='hifz.dailyplan'),
        ),
        migrations.AddField(
            model_name='plansegment',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='quranjourney',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journey', to='people.student'),
        ),
        migrations.AddField(
            model_name='quranjourney',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='journeyevent',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='hifz.quranjourney'),
        ),
        migrations.AddField(
            model_name='dailyplan',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='hifz.quranjourney'),
        ),
        migrations.AddField(
            model_name='ayahstateevent',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayah_events', to='hifz.quranjourney'),
        ),
        migrations.AddField(
            model_name='recitationsession',
            name='halaqah',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='people.halaqah'),
        ),
        migrations.AddField(
            model_name='recitationsession',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='hifz.quranjourney'),
        ),
        migrations.AddField(
            model_name='recitationsession',
            name='plan_segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='hifz.plansegment'),
        ),
        migrations.AddField(
            model_name='recitationsession',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recitationsession',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='people.staff'),
        ),
        migrations.AddField(
            model_name='recitationsession',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='mistakeevent',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mistakes', to='hifz.recitationsession'),
        ),
        migrations.AddField(
            model_name='studentayahstate',
            name='journey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ayah_states', to='hifz.quranjourney'),
        ),
        migrations.AddField(
            model_name='studentayahstate',
            name='tenant',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='mistaketype',
            unique_together={('tenant', 'key')},
        ),
        migrations.AlterUniqueTogether(
            name='dailyplan',
            unique_together={('journey', 'plan_date')},
        ),
        migrations.AddIndex(
            model_name='ayahstateevent',
            index=models.Index(fields=['journey', 'ayah_index', 'occurred_at'], name='hifz_ayah_s_journey_6603c6_idx'),
        ),
        migrations.AddIndex(
            model_name='recitationsession',
            index=models.Index(fields=['journey', 'started_at'], name='hifz_recita_journey_d9e3f4_idx'),
        ),
        migrations.AddConstraint(
            model_name='recitationsession',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key__gt', '')), fields=('tenant', 'idempotency_key'), name='uniq_recitation_idempotency'),
        ),
        migrations.AddIndex(
            model_name='mistakeevent',
            index=models.Index(fields=['session'], name='hifz_mistak_session_136df2_idx'),
        ),
        migrations.AddIndex(
            model_name='mistakeevent',
            index=models.Index(fields=['ayah_index'], name='hifz_mistak_ayah_in_659e9b_idx'),
        ),
        migrations.AddIndex(
            model_name='studentayahstate',
            index=models.Index(fields=['journey', 'next_due_at'], name='hifz_ayah_s_journey_012c2d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentayahstate',
            index=models.Index(fields=['journey', 'state'], name='hifz_ayah_s_journey_8ea47b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='studentayahstate',
            unique_together={('journey', 'ayah_index')},
        ),
    ]
