# Generated by Django 5.1.4 on 2026-09-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hifz', '0003_rls'),
    ]

    operations = [
        migrations.AddField(
            model_name='quranjourney',
            name='juz_map',
            field=models.JSONField(default=list),
        ),
    ]
