# Generated by Django 5.1.4 on 2026-09-08 14:29

import django.db.models.deletion
import services.common.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('center', 'مركز'), ('academy', 'أكاديمية'), ('institution', 'مؤسسة'), ('mosque', 'مسجد'), ('organization', 'منظمة'), ('individual', 'معلم مستقل')], default='center', max_length=20)),
                ('status', models.CharField(default='active', max_length=20)),
                ('plan', models.CharField(default='self_hosted', max_length=40)),
                ('data_region', models.CharField(default='default', max_length=20)),
                ('default_locale', models.CharField(default='ar', max_length=8)),
                ('locales', models.JSONField(default=list)),
                ('timezone', models.CharField(default='Asia/Amman', max_length=64)),
                ('currency', models.CharField(default='JOD', max_length=3)),
                ('calendar', models.CharField(default='both', max_length=12)),
                ('default_riwayah', models.CharField(default='hafs_asim', max_length=32)),
                ('default_mushaf_type', models.CharField(default='madani_15_line', max_length=32)),
                ('branding', models.JSONField(default=dict)),
                ('recording_allowed', models.BooleanField(default=False)),
                ('communication_policy', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'tenants_tenant',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='active', max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='people.person')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_membership',
                'unique_together': {('account', 'tenant')},
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('code', models.CharField(blank=True, max_length=20)),
                ('timezone', models.CharField(blank=True, max_length=64)),
                ('locale', models.CharField(blank=True, max_length=8)),
                ('address', models.JSONField(default=dict)),
                ('gender_policy', models.CharField(default='mixed', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_branch',
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TenantModule',
            fields=[
                ('id', models.UUIDField(default=services.common.models.uuid7, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module_key', models.CharField(max_length=64)),
                ('enabled', models.BooleanField(default=True)),
                ('settings', models.JSONField(default=dict)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant')),
            ],
            options={
                'db_table': 'tenants_module',
                'unique_together': {('tenant', 'module_key')},
            },
        ),
    ]
