# Generated by Django 5.1.4 on 2026-09-09 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_rls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='kind',
            field=models.CharField(choices=[('center', 'مركز'), ('academy', 'أكاديمية'), ('institution', 'مؤسسة'), ('mosque', 'مسجد'), ('organization', 'منظمة'), ('individual', 'معلم مستقل'), ('solo', 'متعلّم مستقل')], default='center', max_length=20),
        ),
    ]
